language: java
sudo: false
install: echo "Skipping install"
script: mvn ${SPARK} ${JAVA} ${SCALA} -Dmaven.javadoc.skip=true -B clean compile
matrix:
 include:
   # Covers Java 7, Oracle JDK, and Spark 1.2.x
   - jdk: oraclejdk7
   # Covers Open JDK, Spark 1.3.x
   - jdk: openjdk7
     env: SPARK=-Pspark-1.3
   # Covers Spark 1.4
   - jdk: openjdk7
     env: SPARK=-Pspark-1.4
   # Covers Spark 1.5, Java 8, Oracle JDK
   - jdk: oraclejdk8
     env: SPARK=-Pspark-1.5 JAVA=-Pjava8
   # Covers Spark 1.6, Scala 2.11
   - jdk: oraclejdk8
     env: SPARK=-Pspark-1.6 JAVA=-Pjava8 SCALA=-Pscala-2.11
   # Covers Spark 2.0
   - jdk: oraclejdk8
     env: SPARK=-Pspark-2.0 JAVA=-Pjava8 SCALA=-Pscala-2.11
cache:
  directories:
    - $HOME/.m2
