language: java
sudo: false
install: echo "Skipping install"
script: mvn ${SPARK} -Dmaven.javadoc.skip=true -B clean compile
jdk: openjdk8
matrix:
  include:
    # Covers Spark 2.3.x
    - env: SPARK=
    # Covers Spark 2.4.x + Scala 2.12
    - env: SPARK="-Pspark-2.4 -Pscala-2.12"
cache:
  directories:
    - $HOME/.m2
